### ISSUE TITLE
Allow escaping any character as opposed to only a predefined list of escaped characters

### ISSUE THREAD

**Issue by hectoralos** [apertium/lttoolbox#103]
Today, after several weeks, I ran testvoc.sh in apertium-fra-frp and I got this crash. I am not able to interpret its message:

```
./testvoc.sh -e
== Arpitan > Français =========================
Error: Malformed input stream./tmp/testvoc.h2cksYCTl7r: line 1:  1973 La canonada s’ha trencat  apertium-pretransfer
      1974 Violació de segment    (la imatge del nucli ha estat bolcada) | lt-proc -b '/home/hector/apertium/apertium-fra-frp/frp-fra.autobil.bin'
```

For sure, the problem is related with the previous issues, although the language pair is another and transfer rules are quite different to apertium-fra-cat, which  caused the issue apertium/apertium#96 and maybe also apertium/apertium#95 (fra-cat is has a one-step transfer while fra-frp has 3+ steps).

**Comment by TinoDidriksen** [comment]
I would say that's a bug. That's an incorrect way to implement reading escaped input. Too much escaping must not be an error or even a warning.

**Comment by khannatanmai** [comment]
I agree. I don't know why it has to be strict with escaping. It's not even consistent with most of the modules. Although with these things I just assume whoever coded it had a use case in their mind so maybe they can tell us.

**Comment by unhammer** [comment]
> I would say that's a bug. That's an incorrect way to implement reading
> escaped input. Too much escaping must not be an error or even a
> warning.

+1

**Comment by khannatanmai** [comment]
I checked the code and the variable escaped_chars is being used **a lot** throughout the code for parsing and a lot of other stuff. Might not be trivial to fix.

**Comment by TinoDidriksen** [comment]
Using it for which characters to escape in output is fine. Using it for which to unescape in input is not. Can't be that hard to change all the input places.

**Comment by khannatanmai** [comment]
Hmm so build up the list of escaped_chars as the input is being read?
