### ISSUE TITLE
postgenerator doesn't work inside word blanks like [[t:text…]]

### ISSUE THREAD

**Issue by unhammer** [apertium/lttoolbox#107]
[nob-nno.autopgen.bin.zip](https://github.com/apertium/apertium/files/5886204/nob-nno.autopgen.bin.zip)
without `[[` works
```
$ echo 'pla~ssar'|lt-proc -p nob-nno.autopgen.bin
plassar
```
as expected, but:
```
$ echo '[[t:text:NaNaNa]]pla~ssar[[/]]'|lt-proc -p nob-nno.autopgen.bin
[[t:text:NaNaNa]]pla~ssar[[/]]
```

(original example from a big docx where there were many words inside the `[[`)

**Comment by khannatanmai** [comment]
@unhammer sorry I've been incredibly busy with my masters thesis and plus there was some talk about post generator being rewritten so I never got around to this. Hope it wasn't too annoying to deal with my wblanks code. Thanks!

**Comment by unhammer** [comment]
no problem, wasn't too big of a change after I put some time into understanding how it worked
