### ISSUE TITLE
segfault in lt-comp

### ISSUE THREAD

**Issue by mr-martian** [apertium/lttoolbox#108]
https://github.com/furusawat/apertium-ain/tree/7bc415e24e37b2f9e807453a440a02513c33fe7a

Likely related to #68

will plan to investigate tomorrow

**Comment by furusawat** [comment]
Maybe because of apertium/apertium-ain#2

My master branch is before the immigration from lexc to lexd, so it is outdated.

**Comment by mr-martian** [comment]
Minimal transducer to reproduce the segfault:

```
0	0	@0@	n	0.000000
0	1	n	@0@	0.000000
1	0.000000
```

Probably the epsilon loop is the issue.
