### ISSUE TITLE
Serializing when size_t != cstdint types

### ISSUE THREAD

**Issue by TinoDidriksen** [apertium/lttoolbox#11]
Build failure on OpenBSD: https://github.com/apertium/apertium/issues/15
Offending commit: https://github.com/apertium/lttoolbox/commit/fb61b829bab0565487320854d0c1c66fc2274071

Need a better way to have size_t separate when size_t is not one of the cstdint types.

**Comment by TinoDidriksen** [comment]
@bentley, this workaround should make OpenBSD happy as well, for now.

**Comment by bentley** [comment]
Seems to work here. Thanks.
