### ISSUE TITLE
allow separable in lt-expand

### ISSUE THREAD

**Issue by unhammer** [apertium/lttoolbox#116]
.lsx is a superset of .dix, shouldn't be too much trouble?

`<w/>` could be written as `<ANY_CHAR>`

`<t/>` could be written as `<ANY_TAG>`

`<j/>` could be written as `$ ^`

**Comment by mr-martian** [comment]
the only tricky things are that you need to check for `<dictionary type="separable">` or `<dictionary type="sequential">` or you need a command line flag so that you know not to treat `<j/>` as `+` and then you probably want final `<j/>` to be just `$`.

**Comment by unhammer** [comment]
> or you need a command line flag so that you know not to treat `<j/>` as `+` and then you probably want final `<j/>` to be just `$`.

… or we could KISS and always have `<j/>` be `+`. That'd probably be just as well.

**Comment by mr-martian** [comment]
As of https://github.com/apertium/apertium-separable/commit/27b8b6a55ced7d7a46ba5b23b3064d47fdf37cec, `<j/>` is `+` in lsx and word-boundary is `<d/>`, so this should be pretty easy.
