### ISSUE TITLE
Failure in corpus test for weighted branch

### ISSUE THREAD

**Issue by Techievena** [apertium/lttoolbox#12]
The corpus test with the `en-es` pair yields different results for master branch and the weighted branch. The difference arises in the apertium-tagger part of the pipeline and after much investigation I have found out that the size of transducers in for the both branches differ.

- Master branch => `Transducer size = 591`
- Weighted branch => `Transducer size = 7`

**Comment by Techievena** [comment]
After modifications due to the PR for issue#3, the output for corpus test differs from these results, but still erronous and yields the same warnings for apertium-tagger.

**Comment by ftyers** [comment]
@Techievena given how little time we have left it might be worth approaching this in the following way:

1. Start a new branch from `master`, call it `weighted-test`.
2. Make a new directory `testing` with two directories `weighted` and `unweighted`
3. In the `weighted` directory check out the `weighted-test` branches of `lttoolbox`, `apertium`, `apertium-lex-tools`, `apertium-spa`, `apertium-cat` and `apertium-spa-cat`.
4. In the `unweighted` directory check out the `master` branches of `lttoolbox`, `apertium`, `apertium-lex-tools`, `apertium-spa`, `apertium-cat` and `apertium-spa-cat`.
5. Compile in both directories with `--prefix` of `weighted/local` and `unweighted/local` and with `PKG_CONFIG_PATH`, `LD_LIBRARY_PATH` and `PATH` set appropriately.
6. Download [this corpus](http://www.gutenberg.org/cache/epub/41161/pg41161.txt)
7. Translate  the text to `cat` using both installations -- the result should be identical.
8. Now start porting over changes from the `weighted` branch to the `weighted-test` branch; every time you make a change (not every line, but let's say every half an hour of work or so), try translating the text to see if the output has changed.

Doing this will tell you which part of your changes are causing the weird new behaviour. In general this should probably be the way to develop.

**Comment by ftyers** [comment]
@Techievena can you show some log output of this working?

**Comment by Techievena** [comment]
@ftyers What kind of log file can I show? I mean the motive was to get an empty diff.
