### ISSUE TITLE
utfcpp

### ISSUE THREAD

**Issue by evvahu** [apertium/lttoolbox#131]
Hi,

I am trying to install the programme and I have successfully installed the dependencies except for utfcpp. I am therefore not able to proceed with 'autogen.sh'
I am working on a ios operation system and my machine has a M1 chip. 
I can download and install the utf8cpp package but that has not resolved the issue. 
I have also looked at this repository but it does not seem be the right one: https://github.com/nemtrif/utfcpp. 
Any suggestions? Does it even work on my machine?

Many thanks!
Eva

**Comment by TinoDidriksen** [comment]
That is the correct repo - you just need the contents of the `source/` folder and then point the build to where to find it.

Everything works on M1 - the [nightly binaries](https://apertium.projectjj.com/osx/) are built for macOS on both x86_64 and M1.
