### ISSUE TITLE
auto-section big fst's for faster compilation

### ISSUE THREAD

**Issue by unhammer** [apertium/lttoolbox#134]
cf. https://github.com/apertium/lttoolbox/pull/133#issuecomment-1080504144
now that we can minimise in parallel, it'd be nice to automatically turn big `<section>`'s into several smaller ones of about the same size. Typically there's one big section and one or two small ones. We can ignore the small ones. We should divide the big one into `core_count` sections (though if doing while parsing and we don't know how many entries there are, a MAX_ENTRIES might be Good Enough).

**Comment by mr-martian** [comment]
Don't know how to divide it evenly, but for the `MAX_ENTRIES` solution, at about here

https://github.com/apertium/lttoolbox/blob/ce94a686a1106c4eae472d3de6b0a8267bd1b2fa/lttoolbox/compiler.cc#L645-L650

```cpp
if (section_sizes[current_section] >= MAX_ENTRIES) {
  current_section = get_other_name(current_section);
  section_sizes[current_section] = 0;
  sections[current_section] = new Transducer();
}

Transducer& t = sections[current_section];
section_sizes[current_section]++;
int e = t.getInitial();
```

**Comment by unhammer** [comment]
Timing this, it seems it's less important to divide it evenly, and more important to just divide it :-)
