### ISSUE TITLE
configure fails because of missing utf8.h

### ISSUE THREAD

**Issue by mortenivar** [apertium/lttoolbox#142]
During the ./configure phase, I got

```
checking for utf8.h... no
configure: error: You don't have utfcpp installed
```
The docs don't mention utfcpp as a dependency. After installing it, I needed to do

 `export CPPFLAGS=-I/usr/include/utf8cpp/`

**Comment by TinoDidriksen** [comment]
Yup. Arch is the odd one out since it puts utfcpp in an unexpected place. This should indeed be fixed.

**Comment by TinoDidriksen** [comment]
Fixed. Also, README has mentioned utfcpp for almost a year.

**Comment by mortenivar** [comment]
Tino Didriksen ***@***.***> wrote:

> Fixed. Also, README has mentioned utfcpp for almost a year.

Okay, somehow I missed it.
