### ISSUE TITLE
lsx-comp --debug 

### ISSUE THREAD

**Issue by unhammer** [apertium/lttoolbox#147]
would be nic eto have something that makes an unminimised .bin that creates an FST per top-level `<e>` and tags the final <r> with the rule number or line number or something

**Comment by mr-martian** [comment]
This would also be useful for postgen.

**Comment by mr-martian** [comment]
Due to limitations of libxml2's `xmlTextReader` interface, I can't insert the actual line number, so I had it insert the approximate line number and the value of the comment attribute (if any).
