### ISSUE TITLE
 Add support for weights to lttoolbox binary format

### ISSUE THREAD

**Issue by ftyers** [apertium/lttoolbox#2]
Start with the `att_compiler`. This means that you won't have to implement determinisation/minimisation code to start with. The code should not break reading existing files. It might be a good idea to have a small one-byte version header. 

Here are a few places to start looking:

**transducer.h:**
```
  /**
   * Transitions of the transducer
   */
  map<int, multimap<int, int> > transitions;
```

**transducer.cc:**
```
void
Transducer::write(FILE *output, int const decalage)

void
Transducer::read(FILE *input, int const decalage)
```

**node.h:**
```
class Node
{
private:
  friend class State;

  /**
   * The outgoing transitions of this node. 
   * Schema: (input symbol, (output symbol, destination))
   */
  map<int, Dest> transitions;
```

@TinoDidriksen do you have any thoughts on properly storing floats in a binary file ?

**Comment by TinoDidriksen** [comment]
Floats can't be stored as-is in a cross-platform manner. They need to be decomposed with [frexp()]to be stored as 2 integers, then on load (http://en.cppreference.com/w/cpp/numeric/math/frexp) and recomposed with [ldexp()](http://en.cppreference.com/w/cpp/numeric/math/ldexp).

Got examples in CG-3: https://github.com/TinoDidriksen/cg3/blob/master/src/inlines.hpp#L456 and https://github.com/TinoDidriksen/cg3/blob/master/src/inlines.hpp#L498

**Comment by Techievena** [comment]
Is the work here mostly replicating the operations currently done in https://github.com/mhulden/foma/blob/master/foma/python/attapply.py in the transducer.h file?
