### ISSUE TITLE
Handle compiling multiple transducers in the same ATT file

### ISSUE THREAD

**Issue by AMR-KELEG** [apertium/lttoolbox#56]
Currently, lt-comp can only compile at&t files containing a single FST.
It would be better if it can also compile multiple disjunct FSTs encoded in the same at&t file.

Example:
```
$ cat transducer.att

--
0       1       a       b       0.000000
1       1.000000
--
0       1       b       c       0.000000
1       1.000000
--
```

The current behaviour is:
```
$ lt-comp lr transducer.att transducer.bin

Error: invalid format 'transducer.att'.
```

**Comment by flammie** [comment]
The actual problem with passing multiple automata in one file or stream is always that you cannot be sure what's the purpose of each automaton, disjunction is just one potential answer, but in context of apertium specifically one could imagine that the different automata are these "incontinent", "standard" etc. parts of dictionaries. Hfst-twolc saves the rule-automata that are to be *conjuncted* in this format.

**Comment by unhammer** [comment]
Since ATT format doesn't include metadata, maybe the best we can do is allow several att files on the command line, e.g. 

`lt-comp lr --inconditional inconditional.att standard.att out.bin`

would turn off the inconditional-guessing and assume anything in `standard.att` goes in a standard section and anything in `inconditional.att` goes in an inconditional section.

**Comment by flammie** [comment]
Yeah I mean ignoring is definitely problematic, at very least lt-comp should warn that it ignores other automata. I think also if lt-comp would automatically disjunct more automata in input, it should print a warning of what it's doing. For the specific case of hfst-compiled stuff this should hint the user to do the disjunct more efficiently on hfst-side (-j or so).

I like the idea of round-trippable automata and some more control over that stuff is also interesting in the hfst2lttoolbox use case.

**Comment by AMR-KELEG** [comment]
I am not sure whether a `--` is allowed to be in the first line.
The patch assumes it isn't allowed.

For the following at&t file:
```
$ cat simple.att
0	1	a	b	0.000000
1	1.000000
--
0	1	b	c	0.000000
1	1.000000
--
```

The output is:
```
$ ./lttoolbox/lt-comp lr simple.att simple.bin
Warning: Multiple fsts in 'simple.att' will be disjuncted.
Warning: Multiple fsts in 'simple.att' will be disjuncted.
main@standard 2 2

$ lt-print simple.bin 
0       1       a       b       0.000000
0       1       b       c       0.000000
1       1.000000

```

**Comment by flammie** [comment]
> I am not sure whether a `--` is allowed to be in the first line.
> The patch assumes it isn't allowed.

It's possible for such -- to appear when automaton is empty such as result of A - A. It's not very useful in NLP probably but can appear in theory books for things. Empty automaton naturally has no effect on disjunction and takes over in conjunction so it probably creates some neat algebra.
 

> The output is:
> 
> ```
> $ ./lttoolbox/lt-comp lr simple.att simple.bin
> Warning: Multiple fsts in 'simple.att' will be disjuncted.
> Warning: Multiple fsts in 'simple.att' will be disjuncted.
> main@standard 2 2
> 
> $ lt-print simple.bin 
> 0       1       a       b       0.000000
> 0       1       b       c       0.000000
> 1       1.000000
> ```

This looks nice.
