### ISSUE TITLE
Python install DESTDIR

### ISSUE THREAD

**Issue by TinoDidriksen** [apertium/lttoolbox#65]
@Vaydheesh (CC @unhammer), when running "make install DESTDIR=/tmp/hubba", the Python parts do not respect that installation prefix.

If I add `--prefix=$(DESTDIR)$(prefix)` to `Makefile.am` install step, an error occurs:
````
make[3]: Entering directory '/misc/lttoolbox/python'
/usr/bin/python3 setup.py install --prefix=/tmp/hubba/usr/local
running install
Checking .pth file support in /tmp/hubba/usr/local/lib/python3.5/site-packages/
/usr/bin/python3 -E -c pass
TEST FAILED: /tmp/hubba/usr/local/lib/python3.5/site-packages/ does NOT support .pth files
error: bad install directory or PYTHONPATH

You are attempting to install a package to a directory that is not
on PYTHONPATH and which Python does not read ".pth" files from.  The
installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /tmp/hubba/usr/local/lib/python3.5/site-packages/
...
Makefile:475: recipe for target 'install-exec-local' failed
````

But libdivvun's https://github.com/divvun/libdivvun/tree/master/python install works with just that, and I don't know why. I don't see any relevant difference, but libdivvun does not run that .pth test step.

**Comment by unhammer** [comment]
One difference is that I run swig from the makefile, not from setup.py – would that fix it @Vaydheesh ?

**Comment by Vaydheesh** [comment]
> One difference is that I run swig from the makefile, not from setup.py – would that fix it

Replacing `setuptools` with `distutils`, fixes this. Should I find a way to  get the things to work with `setuptools` or just switch to  `disutils`

**Comment by TinoDidriksen** [comment]
`distutils` seems to work for everyone else, so I'd say just use that. It looks to be a minimal code change.

**Comment by Vaydheesh** [comment]
Should I create a new branch in `aperium/lttoolbox` for pushing my commits, or generate a PR from my fork?

**Comment by TinoDidriksen** [comment]
Fixed in https://github.com/apertium/lttoolbox/commit/f69d8058328a18555fd64a6fb17210d5d761e80c
