### ISSUE TITLE
Use python3 for tests instead of python2

### ISSUE THREAD

**Issue by AMR-KELEG** [apertium/lttoolbox#70]
Python2 is about to get out of support soon so it would be better if we could update the tests scripts to be python3 complaint.

I tried changing the shebang line to `#!/usr/bin/env python3` and it worked without any issues.
https://github.com/apertium/lttoolbox/blob/1fefd20d9c4c2c88b1d63c160df683a147d5bc53/tests/run_tests.py#L1

We will also need to update the README file.

**Comment by TinoDidriksen** [comment]
The Python module is also only Python 3, so yes everything should drop Python 2 support.

**Comment by AMR-KELEG** [comment]
Thanks @TinoDidriksen 
I pinged you earlier given you are the most active maintainer of lttoolbox :D
