### ISSUE TITLE
3.5.1: cannot find input file: `python/setup.py.in'

### ISSUE THREAD

**Issue by bentley** [apertium/lttoolbox#74]
Testing the uploaded `lttoolbox-3.5.1.tar.gz` on OpenBSD -current.

    Using /ptmp/pobj/lttoolbox-3.5.1/config.site (generated)
    configure: WARNING: unrecognized options: --disable-gtk-doc
    configure: loading site script /ptmp/pobj/lttoolbox-3.5.1/config.site
    checking build system type... x86_64-unknown-openbsd6.6
    checking host system type... x86_64-unknown-openbsd6.6
    checking target system type... x86_64-unknown-openbsd6.6
    checking for a BSD-compatible install... /ptmp/pobj/lttoolbox-3.5.1/bin/install -c
    checking whether build environment is sane... yes
    checking for a thread-safe mkdir -p... mkdir -p
    checking for gawk... (cached) awk
    checking whether make sets $(MAKE)... (cached) yes
    checking whether make supports nested variables... yes
    checking whether the C++ compiler works... yes
    checking for C++ compiler default output file name... a.out
    checking for suffix of executables... 
    checking whether we are cross compiling... no
    checking for suffix of object files... (cached) o
    checking whether we are using the GNU C++ compiler... (cached) yes
    checking whether c++ accepts -g... (cached) yes
    checking for style of include used by make... GNU
    checking dependency style of c++... gcc3
    checking how to print strings... print -r
    checking for gcc... cc
    checking whether we are using the GNU C compiler... (cached) yes
    checking whether cc accepts -g... (cached) yes
    checking for cc option to accept ISO C89... none needed
    checking whether cc understands -c and -o together... yes
    checking dependency style of cc... gcc3
    checking for a sed that does not truncate output... (cached) /usr/bin/sed
    checking for grep that handles long lines and -e... (cached) /usr/bin/grep
    checking for egrep... (cached) /usr/bin/egrep
    checking for fgrep... (cached) /usr/bin/fgrep
    checking for ld used by cc... /usr/bin/ld
    checking if the linker (/usr/bin/ld) is GNU ld... yes
    checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
    checking the name lister (/usr/bin/nm -B) interface... BSD nm
    checking whether ln -s works... yes
    checking the maximum length of command line arguments... (cached) 131072
    checking how to convert x86_64-unknown-openbsd6.6 file names to x86_64-unknown-openbsd6.6 format... func_convert_file_noop
    checking how to convert x86_64-unknown-openbsd6.6 file names to toolchain format... func_convert_file_noop
    checking for /usr/bin/ld option to reload object files... -r
    checking for objdump... objdump
    checking how to recognize dependent libraries... match_pattern /lib[^/]+(\.so\.[0-9]+\.[0-9]+|\.so|_pic\.a)$
    checking for dlltool... no
    checking how to associate runtime and link libraries... print -r --
    checking for ar... (cached) ar
    checking for archiver @FILE support... @
    checking for strip... (cached) strip
    checking for ranlib... (cached) ranlib
    checking command to parse /usr/bin/nm -B output from cc object... ok
    checking for sysroot... no
    checking for a working dd... /bin/dd
    checking how to truncate binary pipes... /bin/dd bs=4096 count=1
    checking for mt... mt
    checking if mt is a manifest tool... no
    checking how to run the C preprocessor... cc -E
    checking for ANSI C header files... (cached) yes
    checking for sys/types.h... (cached) yes
    checking for sys/stat.h... (cached) yes
    checking for stdlib.h... (cached) yes
    checking for string.h... (cached) yes
    checking for memory.h... (cached) yes
    checking for strings.h... (cached) yes
    checking for inttypes.h... (cached) yes
    checking for stdint.h... (cached) yes
    checking for unistd.h... (cached) yes
    checking for dlfcn.h... (cached) yes
    checking for objdir... .libs
    checking if cc supports -fno-rtti -fno-exceptions... yes
    checking for cc option to produce PIC... -fPIC -DPIC
    checking if cc PIC flag -fPIC -DPIC works... yes
    checking if cc static flag -static works... yes
    checking if cc supports -c -o file.o... yes
    checking if cc supports -c -o file.o... (cached) yes
    checking whether the cc linker (/usr/bin/ld) supports shared libraries... yes
    checking whether -lc should be explicitly linked in... yes
    checking dynamic linker characteristics... openbsd6.6 ld.so
    checking how to hardcode library paths into programs... immediate
    checking whether stripping libraries is possible... yes
    checking if libtool supports shared libraries... yes
    checking whether to build shared libraries... yes
    checking whether to build static libraries... yes
    checking how to run the C++ preprocessor... c++ -E
    checking for ld used by c++... /usr/bin/ld
    checking if the linker (/usr/bin/ld) is GNU ld... yes
    checking whether the c++ linker (/usr/bin/ld) supports shared libraries... yes
    checking for c++ option to produce PIC... -fPIC -DPIC
    checking if c++ PIC flag -fPIC -DPIC works... yes
    checking if c++ static flag -static works... yes
    checking if c++ supports -c -o file.o... yes
    checking if c++ supports -c -o file.o... (cached) yes
    checking whether the c++ linker (/usr/bin/ld) supports shared libraries... yes
    checking dynamic linker characteristics... openbsd6.6 ld.so
    checking how to hardcode library paths into programs... immediate
    checking whether build environment is sane... yes
    checking for pkg-config... /usr/bin/pkg-config
    checking pkg-config is at least version 0.9.0... yes
    checking for LTTOOLBOX... yes
    checking whether the compiler supports wide strings... yes
    checking for xmlReaderForFile in -lxml2... no
    checking for ANSI C header files... (cached) yes
    checking for stdlib.h... (cached) yes
    checking for string.h... (cached) yes
    checking for unistd.h... (cached) yes
    checking for stddef.h... (cached) yes
    checking for stdbool.h that conforms to C99... no
    checking for _Bool... no
    checking for an ANSI C-conforming const... (cached) yes
    checking for size_t... (cached) yes
    checking for error_at_line... no
    checking whether fread_unlocked is declared... no
    checking whether fwrite_unlocked is declared... no
    checking whether fgetc_unlocked is declared... no
    checking whether fputc_unlocked is declared... no
    checking whether fputs_unlocked is declared... no
    checking whether fgetwc_unlocked is declared... no
    checking whether fputwc_unlocked is declared... no
    checking whether fputws_unlocked is declared... no
    checking for setlocale... (cached) yes
    checking for strdup... (cached) yes
    checking for getopt_long... (cached) yes
    checking whether C++ compiler accepts -std=c++20... no
    checking whether C++ compiler accepts -std=c++2a... yes
    checking for a Python interpreter with version >= 3.4... python3
    checking for python3... /usr/local/bin/python3
    checking for python3 version... 3.7
    checking for python3 platform... openbsd6
    checking for python3 script directory... ${prefix}/lib/python3.7/site-packages
    checking for python3 extension module directory... ${exec_prefix}/lib/python3.7/site-packages
    checking that generated files are newer than configure... done
    checking that generated files are newer than configure... done
    configure: creating ./config.status
    config.status: error: cannot find input file: `python/setup.py.in'

**Comment by TinoDidriksen** [comment]
`make dist` apparently doesn't include the Python parts. I don't know how to make it do so. @unhammer ?

However, I still really think we should deprecate all use of `make dist`. It is discouraged by every distro, including OpenBSD. The [plain source tarball](https://github.com/apertium/lttoolbox/archive/v3.5.1.tar.gz) is vastly preferred. https://www.openbsd.org/faq/ports/specialtopics.html#Autoconf says "It is better to patch the configure.in file and get the ports tree to call autoconf."

**Comment by bentley** [comment]
You misread the OpenBSD page. In any autotools project, OpenBSD packagers strongly prefer generated configure scripts to avoid running autoconf. Running autoconf as in the advice you quoted is only done when the configure script has bugs and needs to be patched.

In addition, we dislike GitHub’s autogenerated tarballs in particular because they are not guaranteed to have stable checksums. The infrastructure that generates them is brittle and checksums have been known to change in the past.

**Comment by flammie** [comment]
I like using make dist tarballs for gentoo ebuilds too; I'd also recommend using make distcheck perhaps even as travisci script that catches problems like this automatically.
