### ISSUE TITLE
<ig>foo</ig> as sugar for <p><l>foo</l><r><g>foo</g></r></p>

### ISSUE THREAD

**Issue by unhammer** [apertium/lttoolbox#76]
```xml
<e lm="ta ille opp">   <i>t</i><par n="t/a__vblex_adj"/><p><l><b/>ille<b/>opp</l><r><g><b/>ille<b/>opp</g></r></p></e>
```

is very noisy and hard to read, and it's easy to miss a bit from the `<l>` or `<r>` when creating new entries by copy-pasting old ones. It'd be nice to have a syntax sugar so we could instead write

```xml
<e lm="ta ille opp">   <i>t</i><par n="t/a__vblex_adj"/><ig><b/>ille<b/>opp</ig></e>
```
and have it be equivalent to the first example.

**Comment by jimregan** [comment]
Um... I did this, a long long time ago. The patch probably lives in some branch somewhere

**Comment by unhammer** [comment]
on github?

**Comment by jimregan** [comment]
Um... I think lt-comp *has* this

**Comment by jimregan** [comment]
f9dfd9ac4dfd2eac3863630a1f7114ddf7de3b9e

**Comment by unhammer** [comment]
Wow, how did I not notice this … Thanks @jimregan :)
