### ISSUE TITLE
Fix transliteration mode so that it works

### ISSUE THREAD

**Issue by ftyers** [apertium/lttoolbox#8]
We currently have a problem in transliteration mode in that sometimes characters are dropped.

I would like to be able to convert non-alphabetic apostrophes (`U+2019` and `U+0027`) to the alphabetic apostrophe (`U+02BC`) cleanly in the stream without having to rely on `sed`. At the moment I am using:

```
$ cat wiki.txt | sed "s/\([^ ]\)['’]\([^ ]\)/\1ʼ\2/g" | apertium -d  apertium-grn grn-morph
```

If I try and do it in lttoolbox, e.g. using the following transducer:

```
$ lt-print apostrophe.bin 
0	1	a	a	
0	1	á	á	
0	1	ã	ã	
0	1	b	b	
0	1	c	c	
0	1	d	d	
0	1	e	e	
0	1	é	é	
0	1	ê	ê	
0	1	ë	ë	
0	1	ẽ	ẽ	
0	1	f	f	
0	1	g	g	
0	1	h	h	
0	1	i	i	
0	1	í	í	
0	1	ï	ï	
0	1	ĩ	ĩ	
0	1	j	j	
0	1	k	k	
0	1	l	l	
0	1	m	m	
0	1	n	n	
0	1	ñ	ñ	
0	1	o	o	
0	1	ó	ó	
0	1	ô	ô	
0	1	õ	õ	
0	1	p	p	
0	1	q	q	
0	1	r	r	
0	1	s	s	
0	1	t	t	
0	1	u	u	
0	1	ú	ú	
0	1	ü	ü	
0	1	ũ	ũ	
0	1	v	v	
0	1	x	x	
0	1	y	y	
0	1	ý	ý	
0	1	ỹ	ỹ	
0	1	z	z	
1	2	'	ʼ	
1	2	’	ʼ	
2	3	a	a	
2	3	á	á	
2	3	ã	ã	
2	3	b	b	
2	3	c	c	
2	3	d	d	
2	3	e	e	
2	3	é	é	
2	3	ê	ê	
2	3	ë	ë	
2	3	ẽ	ẽ	
2	3	f	f	
2	3	g	g	
2	3	h	h	
2	3	i	i	
2	3	í	í	
2	3	ï	ï	
2	3	ĩ	ĩ	
2	3	j	j	
2	3	k	k	
2	3	l	l	
2	3	m	m	
2	3	n	n	
2	3	ñ	ñ	
2	3	o	o	
2	3	ó	ó	
2	3	ô	ô	
2	3	õ	õ	
2	3	p	p	
2	3	q	q	
2	3	r	r	
2	3	s	s	
2	3	t	t	
2	3	u	u	
2	3	ú	ú	
2	3	ü	ü	
2	3	ũ	ũ	
2	3	v	v	
2	3	x	x	
2	3	y	y	
2	3	ý	ý	
2	3	ỹ	ỹ	
2	3	z	z	
3
```

I get:

```
$ echo "ka'aguy" | lt-proc -t apostrophe.bin 
a'gy
```

The expected output is:

```
$ echo "ka'aguy ka'aguy" | lt-proc -t apostrophe.bin 
kaʼaguy kaʼaguy 
```

**Comment by ftyers** [comment]
This could also potentially be done inside lttoolbox itself by trying to step with `U-02BC` any time the input symbol is `U-2019` or `U-0027`. That might in fact be a cleaner way of doing it. What do people think? @unhammer @flammie

**Comment by TinoDidriksen** [comment]
Homoglyph stepping could be a general addition to lttoolbox: https://github.com/codebox/homoglyph

If actual input isn't found, fall back on a homoglyph.

**Comment by flammie** [comment]
the only thing I am worried about is that it needs to be done in a way that doesn't surprise the user and can be tuned or turned off. Like if acronym N0 is missing from analyser I don't want it to turn to a "no" because of that or if it does I want to know why and how to override it, and if for example you''d work with a language that has three different apostrophes with different meanings you surely don't want them mixed up.
