### ISSUE TITLE
escape special symbols in lt-expand?

### ISSUE THREAD

**Issue by unhammer** [apertium/lttoolbox#82]
Perhaps lt-expand should escape e.g. `:` as part of form/lemma (`DJ:en:DJ<n><m><sg><def>` looks like it has three fields). Similarly other [reserved chars ](http://wiki.apertium.org/wiki/Apertium_stream_format)

**Comment by ftyers** [comment]
I wonder if we shouldn't also be able to compile `lt-expand`ed dictionaries. It could be just another optional format for `lt-comp`.

**Comment by MarcRiera** [comment]
Reserved characters are still not escaped if they are part of a regular expression. Take the following example, which includes `:` and becomes difficult to process unless overly complicated regex is used. Otherwise, it looks like it has 4 fields:

`__REGEXP__[.\?;:!]+:__REGEXP__[.\?;:!]+<sent>`

**Comment by mr-martian** [comment]
It will now escape `^$/<>{}*@#+~:` in regexes. Let me know if that list should be any different.

**Comment by MarcRiera** [comment]
Thanks!
