### ISSUE TITLE
A symbol for morpheme boundary

### ISSUE THREAD

**Issue by ftyers** [apertium/lttoolbox#89]
The compiler should compile it out by default but there should be an option to retain them to lt-comp. This can be used to make e.g. segmenters. It is needed because at the moment many languages get around `.dix` restrictions by just duplicating entries, so we can't just add morpheme boundary symbols to the beginning of `<l>` sides (although that works nicely for paradigms.
```
    <e lm="parastin"><p><l>parast</l><r>parastin</r></p><par n="kir/__vblex_tv"/></e>
    <e lm="parastin"><p><l>diparast</l><r>parastin</r></p><par n="dikir/__vblex_tv"/></e>
    <e lm="parastin"><p><l>diparêz</l><r>parastin</r></p><par n="dik/e__vblex_tv"/></e>
    <e lm="parastin"><p><l>biparêz</l><r>parastin</r></p><par n="bik/e__vblex_tv"/></e>
    <e lm="parastin"><p><l>neparast</l><r>parastin</r></p><par n="nekir/__vblex_tv"/></e>
    <e lm="parastin"><p><l>naparêz</l><r>parastin</r></p><par n="nak/e__vblex_tv"/></e>
    <e lm="parastin"><p><l>neparêz</l><r>parastin</r></p><par n="nek/e__vblex_tv"/></e>
```
this would give segmentations like `biparêz>in` for `bi>parêz>in`. So it would be nice to be able to give explicit morpheme boundaries. Option (1) is that there are a few single letters left, `c d f h k m n o q t u v w x y z`, here is what the code looks like with each of them:  
[examples.txt](https://github.com/apertium/lttoolbox/files/4807514/examples.txt)

Ideally we could come up with something with a good mnemonic too. 
* `<m/>` *muga* "border" (Basque)
* `<f/>` *frontera* "border" (Catalan)
* `<f/>` *finis* "border" (Latin)
* `<h/>` *hranice* "border" (Czech), *határ* "border" (Hungarian)

Another option (2) would be to use a XML entity or (3) a simple Unicode symbol, like `¦` or `‖`.

**Comment by mr-martian** [comment]
`<m/>` for "morpheme boundary" works in English as well.

**Comment by khannatanmai** [comment]
I would say that if I've to mark morpheme boundaries then <m/> each time sounds like a bit more work than needed, so I'd think that a symbol might be easier to work with. <m/> would be consistent though so I if we're okay with typing <m/> for all morpheme boundaries (including for the really agglutinative languages), then that sounds good too.

**Comment by ftyers** [comment]
For really agglutinative languages then generally HFST is used. This is more for fusional languages that are done in lttoolbox. And I wouldn't necessarily do this manually, I'd be more inclined to approximate it, at least for existing transducers.

**Comment by unhammer** [comment]
The only shorter XML option would be an entity, wouldn't it? `&m;` or whatever. But that would look a bit ugly, especially considering we don't use entities for anything else. I think `<m/>` works ok – hopefully most uses would be inside pardefs anyway. 

I don't think we should reserve a unicode symbol, feels like a lexcy hack – the good thing about XML is that we have a metalanguage that lets us do things like this, unambiguously saying what level something should be interpreted at.

**Comment by ftyers** [comment]
@unhammer yep I agree. Ok then, `<m/>` it is!

**Comment by ftyers** [comment]
Here is some motivation for future reference:
```
12:34 <+xavivars> spectie, what's the benefit of this feature? What's its usage?
12:35 <+spectie> xavivars: it's part of the work on weighting transducers 
12:35 <+spectie> so mostly with lttoolbox transducers, they're unweighted
12:36 <+spectie> so any analysis could be equally valid
12:36 <+spectie> but we know that that isn't the case 
12:36 <+spectie> mostly some analyses are more probable than others
12:36 <+spectie> so we could weight the transducers, either manually (by explicitly picking out the more valid --- or less valid analyses)
12:36 <+spectie> or we could weight them with a corpus
12:36 <+spectie> but both of those things require quite a lot of human intervention 
12:37 <+spectie> so it would be cool to have a way of weighting them that was unsupervised 
12:37 <begiak> spectie: unsupervised
12:37 <+spectie> exactly, begiak 
12:38 <+spectie> in neural machine translation, vocabulary is reduced using a technique called 'BPE', this is basically a compression technique that tries to encode a corpus in a given vocabulary size 
12:38 <+spectie> the downside to BPE is that the segments it makes are not necessarily linguistically informed
12:38 <+spectie> but it does do a very good job of segmentation in general (e.g. translation performance is higher using BPE than without or with other techniques)
12:39 <+spectie> so, how do these fit together? 
12:40 <+spectie> if we are able to define the valid segments in the .dix files (or .lexc files) then we can use BPE to generate segments and frequencies, and then use those to weight the transducers
12:41 <+spectie> it won't be as good as tagging a corpus
12:41 <+spectie> and weighting based on that
12:41 <+spectie> but it will be better than uniform/selecting randomly
12:41 <+spectie> and all you'll need is a raw corpus
12:42 <+spectie> i've tested the method out on a small scale with k'iche', but i'd like to try it with some other languages and not just HFST-based ones
```
